--- 
title: Cough Syrup
---

\titledquestion{Cough Syrup}[5]

A random sample of $50$ bottles of a particular brand of cough syrup is selected and the alcohol content (in milligram) of each bottle is determined. Let $\mu$ denote the average alcohol content for the population of all bottles of the brand. Suppose that the resulting 95\% confidence interval for $\mu$ is $(7.8, 9.4)$.

Select all the TRUE statements below.

\begin{checkboxes}
\choice 95\% of the bottles of this type of cough syrup have an alcohol content from 7.8 to 9.4 milligrams. 
\choice There is a 95\% chance that $\mu$ is between 7.8 and 9.4 milligrams. 
\choice We can be highly confident that 95\% of all bottles of this type of cough syrup have an alcohol content that is between 7.8 and 9.4 milligrams. 
\CorrectChoice If we repeat the process of selecting a sample of size $50$ bottles and then computing the corresponding 95\% confidence intervals for many times, then 95\% of the resulting intervals will include $\mu$.
\CorrectChoice If we increase the confidence level to 99\%, the confidence interval will be wider.
\choice The 95\% confidence interval is NOT valid as the population distribution of the alcohol content may not be normal.
\choice If we repeat the process of selecting a sample of size $50$ bottles and then computing the average alcohol content of the selected $50$ bottles, 95\% of these sample means will be between $7.8$ and $9.4$.
\choice If we test the null hypothesis that the average alcohol content of this type of cough syrup is $8$ milligrams, the two-sided p-value will be below $0.05$ and we will reject the null hypothesis.
\CorrectChoice The margin of error for the 95\% confidence interval (7.8, 9.4) is 0.8.
\choice We can reduce the margin of error by half if we double the sample size.
\end{checkboxes}